

# User :: Create (Sign Up)
POST {{baseUrl}}/auth/signup HTTP/1.1
content-type: application/json

{
    "name": "Joao",
    "email": "joaopaulofurtado@live.com",
    "phone": "778 846 7427",
    "address": "1010 6th Ave, New Westminster",
    "password": "123456",
    "passwordConfirmation": "123456"
}

###
